baseURL = "http://elmah.ir/"
languageCode = "fa-ir"
title = "elmah"
theme = "nuo"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true

[params]  
  author = "حامد سعیدی فرد"
  avatar = "https://avatars1.githubusercontent.com/u/1385656?s=460&v=4"
  seotitle = "ELMAH"
  subtitle = "~ یادداشت‌های یک برنامه‌نویس خوشحال ~"
  description = ""
  paginate = 15

  github = "hameds"
  twitter = "hamed"  

# Copyright of your post
copyright = ""

# Google Analytics UA number
googleAnalytics = "UA-109151384-1"

[[menu.main]]
  name = "صفحه نخست"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "پرزنت‌های من"
  weight = 15
  identifier = "presentations"
  url = "https://hameds.github.io/slides/"